spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
            - Path=/ai
          filters:
            - RewritePath=/ai/(?<path>.*),/$\{path}
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8070/eureka/
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8072